settings:
  title: '站点状态'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-ziyuanxiong-cn # unique identifier
    name: www.ziyuanxiong.cn
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://ziyuanxiong.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-xibel-cn
    name: www.xibel.cn
    description: 'Built for anything connected to the Internet.'
    url: 'https://xibel.cn'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: www-tuha-ru
    name: www.tuha.ru
    url: 'https://www.tuha.ru/'
    method: GET
    expectStatus: 200

  - id: home-ziyuanxiong-cn
    name: home.ziyuanxiong.cn
    description: 'Built for anything connected to the Internet.'
    url: 'https://home.ziyuanxiong.cn'
    method: GET
    expectStatus: 200
    linkable: true

  - id: www-xibel-us-kg
    name: xibel.us.kg
    description: 'Built for anything connected to the Internet.'
    url: 'https://xibel.us.kg'
    method: GET
    expectStatus: 200
    linkable: true

  - id: tc-ysou-cc
    name: tc.ysou.cc
    description: 'Built for anything connected to the Internet.'
    url: 'https://tc.ysou.cc'
    method: GET
    expectStatus: 200
    linkable: true
